version: '3.8'

services:
  frontend:
    image: quote-generator-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "/api/quote"

  backend:
    image: quote-generator-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
